### ISSUE TITLE
测试时报错：register_template() got an unexpected keyword argument 'replace_eos'

### ISSUE THREAD

**Issue by zig-kwin-hu** [zjunlp/IEPile#33]
您好，我在用oneke模型做inference时，发生报错如下：
Traceback (most recent call last):
  File "/storage/zkhu/IEPile-main/src/inference.py", line 11, in <module>
    from datamodule.preprocess import preprocess_dataset
  File "/storage/zkhu/IEPile-main/src/datamodule/preprocess.py", line 6, in <module>
    from datamodule.template import get_template_and_fix_tokenizer
  File "/storage/zkhu/IEPile-main/src/datamodule/template.py", line 721, in <module>
    register_template(
TypeError: register_template() got an unexpected keyword argument 'replace_eos'

检查后发现，register_template这个函数没有replace_eos这个参数，是bug吗？

**Comment by zxlzr** [comment]
请问您是按照https://github.com/zjunlp/IEPile/blob/main/requirements.txt 版本安装的依赖库吗

**Comment by guihonghao** [comment]
你好，我们已在最新的代码中修改了该错误。

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
